# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WtUZz_nbShXc15tZVBqEOR5VsO_bCqNq
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn import metrics

from google.colab import files
uploaded = files.upload()  # Îți permite să încarci fișierul direct din calculator.

car_dataset = pd.read_csv('carzz_data.CSV',sep=";")

car_dataset.head()

car_dataset.info()

car_dataset.isnull().sum()

car_dataset.shape

print(car_dataset.tip_combustibil.value_counts())
print(car_dataset.tip_caroserie.value_counts())
print(car_dataset.tip_cutie_de_viteza.value_counts())

"""Encoding"""

car_dataset.replace({'tip_combustibil':{'Diesel':0,'Benzin?':1,'Electric':2,'Hibrid':3,'GPL':4}},inplace=True)
car_dataset.replace({'tip_caroserie':{'SUV':0,'Hatchback':1,'Berlin?':2,'Break':3,'Monovolum':4,'Coupe':5,'Microbuz':6,'Limuzin?':7,'Autovehicul mic':8,'Cabrio':9,'Pick-up':10}},inplace=True)
car_dataset.replace({'tip_cutie_de_viteza':{'Automat?':0,'Manual?':1,'Automat? (CVT)':2,'Automat? (dublu ambreiaj)':3,'Semi-automat?':4}},inplace=True)

pd.set_option('future.no_silent_downcasting', True)

car_dataset['marca_masina'].unique()

car_dataset.replace({'marca_masina':{'Mazda':0, 'Audi':1, 'Peugeot':2, 'Opel':3, 'Dacia':4, 'Ford':5,
       'Jeep':6, 'Kia':7, 'BMW':8, 'Skoda':9, 'Skoda':10, 'Mercedes-Benz':11,
       'Renault':12, 'SsangYong':13, 'Citroen':14, 'Toyota':15, 'Nissan':16, 'Hyundai':17,
       'Jaguar':18, 'Land Rover':19, 'Suzuki':20, 'Porsche':21, 'Volvo':22, 'Alfa Romeo':23,
       'Seat':24, 'Fiat':25, 'Dodge':26, 'Chevrolet':27, 'Mitsubishi':28, 'Mini':29, 'Bentley':30, 'Alta':31, 'Infiniti':32, 'Honda':33, 'Lexus':34, 'Daewoo':35, 'Tesla':36,'Volkswagen':37}},inplace=True)

car_dataset.head()

"""Splitting the data and target"""

x=car_dataset.drop(['pretul'],axis=1)
y=car_dataset['pretul']

print(x)

print(y)

"""Splitiing Training and Test data"""

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)

"""Model training

Linear regression
"""

lin_reg_model = LinearRegression()

lin_reg_model.fit(x_train,y_train)

"""Model evaluation Training"""

training_data_prediction=lin_reg_model.predict(x_train)

error_score=metrics.r2_score(y_train,training_data_prediction)
print("R squared error: ",error_score)

"""testing"""

testing_data_prediction=lin_reg_model.predict(x_test)

error_score_test=metrics.r2_score(y_test,testing_data_prediction)
print("R squared error test: ",error_score_test)

import pickle as pk

pk.dump(lin_reg_model,open('model.pkl','wb'))